In [1]:
import numpy as np


In [ ]:
## We can create an array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
## we can reshape the array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
##2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
## we can create array with start with 0 end with 10 and jump with 2 
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
## we can create array with start with 0 end with 10 and jump with 2  and reshape it
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
## We can create array with only 1's
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
## We can create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:\n",arr.shape)
print("Number of dimensions:\n",arr.ndim)
print("Size(number of elements):\n",arr.size)
print("Data type:\n",arr.dtype)
print("Item size:\n",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of dimensions:
 2
Size(number of elements):
 6
Data type:
 int64
Item size:
 8


In [20]:
## We can perform the arithemetic operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("Addition:\n",arr1+arr2)
print("Subtract:\n",arr1-arr2)
print("Multiplication:\n",arr1*arr2)
print("Division:\n",arr2//arr1)

Addition:
 [11 22 33 44 55]
Subtract:
 [ -9 -18 -27 -36 -45]
Multiplication:
 [ 10  40  90 160 250]
Division:
 [10 10 10 10 10]


In [21]:
## We can create Universal function
import math
arr=np.array([2,3,4,5,6])
print("Square:\n",np.sqrt(arr))
print("Exponential:\n",np.exp(arr))
print("Sin:\n",np.sin(arr))
print("Log:\n",np.log(arr))

Square:
 [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:
 [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sin:
 [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log:
 [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [22]:
## Array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[0])

[1 2 3 4]


In [25]:
print(arr[0][0])

1


In [27]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [29]:
## modify array element
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
##Statistical concepts  Normalization
## To have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])
mean=np.mean(data)
print(mean)
sta_dev=np.std(data)
print(sta_dev)
normalize_data=(data-mean)/sta_dev
print("Normalized data:\n",normalize_data)

variance=np.var(arr)
print(variance)

3.0
1.4142135623730951
Normalized data:
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
669.8541666666666


In [32]:
## We can perform logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
print(data[data>5])

[ 6  7  8  9 10]
